[profile.default]
src = "contracts"
test = "test/foundry"
out = "foundry-out"
cache_path = "foundry-cache"
libs = ["node_modules", "lib"]
solc = "0.8.28"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@coti-io/coti-contracts/=node_modules/@coti-io/coti-contracts/",
    "forge-std/=lib/forge-std/src/",
]
